# Generated by Django 3.1.4 on 2020-12-10 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('owner_email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('contact_date', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
