# Generated by Django 3.1.4 on 2020-12-11 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20201210_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='owner_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
